### PR TITLE
[MRG] switch to pytest

### PR DESCRIPTION
**Pull request by pavanramkumar**

### CODE REVIEW

**Comment by pavanramkumar** [comment]
closes #256

**Comment by jasmainak** [comment]
@pavanramkumar make sure to update the `Makefile` and all relevant docs as well (contributing.md etc.)

**Comment by jasmainak** [comment]
@pavanramkumar ready to merge?

**Comment by pavanramkumar** [comment]
@jasmainak 
- are you sure that `python setup.py develop` is the way to go here?
- any changes to be made in documentation before we merge?

**Comment by pavanramkumar** [comment]
- seems `python setup.py develop` is ok for virtualenvs such as travisCI environment: https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install
- i also edited the developer docs to use pytest

merging.

**Pull request merged**
