### PR TITLE
Python2 import fix in datasets.py

### PR DESCRIPTION
**Pull request by cxrodgers**
This PR fixes an import of urllib for Python 2, without compromising Python 3 functionality.
https://github.com/glm-tools/pyglmnet/issues/292

### CODE REVIEW

**Comment by jasmainak** [comment]
Is this really necessary? Python 2 is not going to be supported be most libraries soon including numpy. It's going to be a pain to maintain ...

**Comment by cxrodgers** [comment]
No, it is not necessary. But it might help some people. But I understand if you don't want to include such a workaround.

**Comment by jasmainak** [comment]
I think getting pretty much anything done in scientific Python 2 would be difficult very soon since numpy won't be supported ...

**Comment by jasmainak** [comment]
let's close this PR? would be better to focus the efforts on other development aspects than to support this

**Pull request closed without merging**
