### PR TITLE
Add check for readme to travis

### PR DESCRIPTION
**Pull request by yathomasi**
added check for readme to travis but it failed with error. issue #337

### CODE REVIEW

**Comment by jasmainak** [comment]
let us know when it works. It's probably that you don't have the right version of `twine`. So, you might want to print the version of `twine` on travis and upgrade it if necessary

**Comment by yathomasi** [comment]
I tried running locally
`➜ twine check dist/*`
Checking dist/pyglmnet-1.2.dev0-py3-none-any.whl: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 11: Warning: "raw" directive disabled.
Checking dist/pyglmnet-1.2.dev0.tar.gz: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 11: Warning: "raw" directive disabled.

**Comment by jasmainak** [comment]
right, I would expect to see the same error on Travis but currently it's not the case.

**Comment by jasmainak** [comment]
closing this as you deleted the fork

**Pull request closed without merging**
