### PR TITLE
Remove unused function

### PR DESCRIPTION
**Pull request by jasmainak**

### CODE REVIEW

**Comment by pavanramkumar** [comment]
Rationale of `_L2loss()`: 

We compute gradients on the differentiable part of the loss function (`_L2loss`). In our current implementation, we calculate all gradients manually, but in the future, if we choose to implement automatic differentiation, a function for the L2 loss will be very useful.

Should we edit the docstring to make this clear?

**Comment by jasmainak** [comment]
oh okay got it. But having unused functions can be confusing. We should try to avoid this as much as possible ... I guess I can integrate it with the other PR: https://github.com/glm-tools/pyglmnet/pull/187.

And maybe we should call it `_reconstruction_loss` not `L2loss` ?

**Comment by pavanramkumar** [comment]
But it includes both the likelihood loss and the L2 regularizer loss.

**Comment by jasmainak** [comment]
oops, read it too fast :) okay got it now

**Pull request closed without merging**
