### PR TITLE
Add small example of usage in the JOSS paper.

### PR DESCRIPTION
**Pull request by geektoni**
I have added a small example of how to use pyglmnet in the JOSS paper (by taking inspiration from [one](https://glm-tools.github.io/pyglmnet/auto_examples/plot_community_crime.html#sphx-glr-auto-examples-plot-community-crime-py) of the already existing examples in the gallery).

The final pdf can be found [here](https://github.com/glm-tools/pyglmnet/files/4108566/c84xmzrfsmhx3wfqeznd.pdf).

### CODE REVIEW

**Comment by jasmainak** [comment]
thanks a lot @geektoni !

I am just waiting for the editor to give his comments before going ahead and editing the paper :)

**Comment by geektoni** [comment]
> thanks a lot @geektoni !
> 
> I am just waiting for the editor to give his comments before going ahead and editing the paper :)

makes sense to me :+1:

**Comment by geektoni** [comment]
I was thinking about adding also the plot presented in the example to the document, just to give more contest about the code usage. Would it be worth it or does it just bloat the paper?

**Comment by jasmainak** [comment]
@geektoni have you disabled pushing by maintainers to your branch? Looks like I can't fix the CircleCI issue you got. I'll just open a new PR

**Comment by geektoni** [comment]
> @geektoni have you disabled pushing by maintainers to your branch? Looks like I can't fix the CircleCI issue you got. I'll just open a new PR

mmh the “allow edit feature” is enabled for this PR. No idea why you cannot edit it :/. Go ahead with the new PR since I think it’s faster

**Comment by jasmainak** [comment]
oh I got the branch name wrong it seems. It's `feature/improve-pr` not `improve-pr`. Never mind, we'll continue in the new PR anyway

**Comment by geektoni** [comment]
Ah I see! I’ll close this one since it not useful anymore.

**Pull request closed without merging**
