### PR TITLE
DOC: improve readme example

### PR DESCRIPTION
**Pull request by jasmainak**
@pavanramkumar @titipata @geektoni here is my attempt at improving the readme example. Let me know what you think

### CODE REVIEW

**Comment by pavanramkumar** [comment]
thanks for going the extra mile as always @jasmainak!

**Comment by jasmainak** [comment]
@titipata I'll go ahead and merge for now. Feel free to make a follow up PR if you want to improve it!

**Comment by geektoni** [comment]
Looks good to me! :+1:  I would just add `plt.plot()` at the end of the example to actually visualize the plots. If a user copy-pastes the code now he won't see any graph displayed.

**Comment by titipata** [comment]
Agree with @geektoni, otherwise this looks good to me! I'll make the PR if seeing some more improvement @jasmainak

**Pull request merged**
