### PR TITLE
Make grid search cv work

### PR DESCRIPTION
**Pull request by jasmainak**

### CODE REVIEW

**Comment by pavanramkumar** [comment]
this is awesome! do you want to make a quick example along with this PR?

**Comment by mvogelsang** [comment]
I am confused seeing this, the description on PyPI claims that this package already works generically GridsearchCV. This package, does, however seem to be exactly what I'm looking for. Should we just keep to the slicing methodology for now?

**Comment by pavanramkumar** [comment]
@mvogelsang the slicing approach made it hard to reconcile with other aspects of scikit-learn API (`ElasticNet` vs. `ElasticNetCV`), hence in a recent hackathon we decided to abandon it.

If you'd like to do cross-validation for optimal regularization, I recommend the new `GLMCV` class.

**Comment by jasmainak** [comment]
@pavanramkumar I updated the example. But the pseudo-R2 is very different from what we were getting from GLMCV. It's around 137. Is that a reasonable number?

**Comment by jasmainak** [comment]
@pavanramkumar rebased. I'm sure you want to review this PR when you want a break from work ;)

**Pull request merged**
