### PR TITLE
approximate gradients / hessians for probit to prevent over/underflow

### PR DESCRIPTION
**Pull request by pavanramkumar**

### CODE REVIEW

**Comment by pavanramkumar** [comment]
closes #243

**Comment by jasmainak** [comment]
@pavanramkumar Travis is not happy.

are you sure it's an underflow/overflow problem? Because the gradient checks are fine.

**Comment by pavanramkumar** [comment]
@jasmainak i think it depends in what range we're checking the gradients. 

are you able to plot the loss on `master`? i'm deducing over/underflow because the loss is running into `nan`s

my hypothesis is:
- the approximate gradients i'm calculating are not good enough to pass the gradient checks. 
- the approximate gradients also don't guarantee that the loss decreases steadily.
- but they are good enough because the accuracy test for `beta` passes.

let me explicitly check the betas.

**Comment by pavanramkumar** [comment]
@jasmainak made some more changes for the gradient check. approximate logL to prevent under/overflow did the trick. 

See Eq. (17-20) here: https://pdfs.semanticscholar.org/0c03/0537919f09575b9f2c0a98c62f6571bdceee.pdf

I also did some better nan checks and reintroduced the "loss always decreases" test for probit/cdfast which I had commented out in the previous commit.

Tests pass!

**Comment by jasmainak** [comment]
@pavanramkumar I'm happy if Travis is happy :) I didn't look closely at the equations but I'm confident it's correct.

**Comment by jasmainak** [comment]
might have been worth it to put a link to the paper in the comments, as otherwise someone looking at the code in the future may be lost ...

**Pull request merged**
